apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: <node_pool_name>
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-type
          operator: In
          values: <InstanceTypeList>

      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: <node_class_ref>
      expireAfter: 720h 
  limits:
    cpu: <cpu_limit>
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m