apiVersion: karpenter.k8s.aws/v1 
kind: EC2NodeClass 
metadata: 
  name: <node_class_name> 
  metadataOptions:
spec: 
  role: <node_instance_role> 
  metadataOptions:
    httpPutResponseHopLimit: 2
  amiSelectorTerms: 
    - name: <ami_name> 
  subnetSelectorTerms: 
    - tags: 
        karpenter.sh/discovery: 'true'

  securityGroupSelectorTerms:
    - tags: 
        karpenter.sh/discovery: <cluster_name>

  



      

